name: Github Pages Deploy

on:
  push:
    branches:
      - "master"
  

jobs:
  build:
    run-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@1
      
      - name: Install and Build
        run: npm install && npm run build
      
      - name: Deploy
      